### ISSUE TITLE
Is this Maintained?

### ISSUE THREAD

**Issue by RyanZim** [rocktemplates/rock#11]
@jprichardson This looks great, but the last commit was 2013.

**Comment by jprichardson** [comment]
Hi @RyanZim I haven't been maintaining it. I still love the idea behind it. Basically to scaffold out files, folder structures crazy quickly. If you're interested in helping, I'd embrace it. @alabastida had some interest in possibly helping, but I've done a horrible job following through. Sorry guys on the responses, I just launched https://www.exodus.io/ a month ago and I'm getting buried from the influx of attention. But I'm to any ideas you guys have.

**Comment by RyanZim** [comment]
Sounds great; I haven't done much fooling with it, but so far, so good.

**Comment by alabastida** [comment]
Hi guys, Im actually using rock with a custom CLI tool im buidling to create parametrized angular components on the fly including js, less, jade and html files, had a little trouble making it work on windows and it was due to the use of a certain action in the github-download dependency which I fixed and I was able to make it work there, probably the actual github-download version is already fixed, haven’t had the time to check tho.

I wiould like to continue working on this idea it is promising and really easy to do, would like to give it a shot.

Regards,
Adrian Labastida
labastida@gmail.com

**Comment by RyanZim** [comment]
One question/suggestion: Is there a naming convention for "rocks"? yeoman uses `generator-`, slush uses `slush-`, what about rock?

**Comment by jprichardson** [comment]
Currently I use `rock-`, but I've never published them to npm since it pulls from `github`. Although I'm fine with incorporating and publishing them to npm if you guys think it's better.

**Comment by RyanZim** [comment]
> Although I'm fine with incorporating and publishing them to npm if you guys think it's better. 

Absolutely not! That is one of my pet peeves with yeoman; installing all the generators with `-g`.

**Comment by RyanZim** [comment]
Another question:

Some of your rocks include a `.rock` directory. What does this do?

**Comment by alabastida** [comment]
From what I learnt, int the .rock folder you can contain a rock.config.json file where you can define default values for your templates and other config options like the delimiters and some more, it’s all there in the rock documentation.

Regards,
Adrian Labastida
labastida@gmail.com
Mobile: (+52) 81 80888750

**Comment by RyanZim** [comment]
@alabastida Yeah, I knew about `~/.rock`, I was wondering about https://github.com/rocktemplates/rock-node-bin/tree/master/.rock

**Comment by RyanZim** [comment]
Well, this is now quite well maintained, so closing this. :smiley_cat:
